global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alert manager would be configured here

rule_files:
  # Rules would be added here

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    
  - job_name: 'petclinic'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic:8080']