---
- name: Deploy PetClinic Application
  hosts: petclinic
  become: yes
  vars:
    app_name: petclinic
    app_user: petclinic
    app_group: petclinic
    app_home: /opt/petclinic
    java_package: openjdk-17-jdk

  tasks:
    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
        update_cache: yes
      register: java_install
      until: java_install is success
      retries: 3
      delay: 5

    - name: Ensure application group exists
      group:
        name: "{{ app_group }}"
        state: present

    - name: Ensure application user exists
      user:
        name: "{{ app_user }}"
        group: "{{ app_group }}"
        shell: /bin/bash
        home: "/home/{{ app_user }}"
        createhome: yes
        state: present

    - name: Create application directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      with_items:
        - "{{ app_home }}"
        - "{{ app_home }}/config"
        - "/var/log/{{ app_name }}"

    - name: Copy application JAR file
      copy:
        src: files/petclinic.jar
        dest: "{{ app_home }}/petclinic.jar"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0500'
      notify: restart petclinic

    - name: Copy application configuration
      template:
        src: application.properties.j2
        dest: "{{ app_home }}/config/application.properties"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0400'
      notify: restart petclinic

    - name: Copy systemd service file
      template:
        src: petclinic.service.j2
        dest: /etc/systemd/system/petclinic.service
        owner: root
        group: root
        mode: '0644'
      notify: restart petclinic

    - name: Ensure service is enabled and started
      systemd:
        name: petclinic
        daemon_reload: yes
        enabled: yes
        state: started

  handlers:
    - name: restart petclinic
      systemd:
        name: petclinic
        state: restarted